module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.module.ts',
    '!src/main.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.entity.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.constants.ts',
    '!src/common/testing/**/*.ts',
    '!src/**/index.ts',
    '!src/**/*.decorator.ts',
    '!src/**/*.strategy.ts',
    '!src/infrastructure/database/prisma.service.ts',
    '!src/**/*.guard.ts',
    '!src/**/*.controller.ts',
    '!src/**/*.interceptor.ts',
  ],
  coverageDirectory: './coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@common/(.*)$': '<rootDir>/src/common/$1',
    '^@core/(.*)$': '<rootDir>/src/core/$1',
    '^@business/(.*)$': '<rootDir>/src/business/$1',
    '^@platform/(.*)$': '<rootDir>/src/platform/$1',
    '^@agentic/(.*)$': '<rootDir>/src/agentic/$1',
    '^@infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/test/integration/', '/test/e2e/'],
};
